{% set name = "gfabase" %}
{% set version = "0.6.0" %}
{% set sha256 = "d17ef77d2f57ace316a7b35d910c5cd73be2a0d70ec7fcd31f2d0e3afbe1273c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mlin/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('gfabase', max_pin="x.x") }}

requirements:
  build:
    - git
    - rust

test:
  commands:
    - gfabase -h

about:
  home: https://github.com/mlin/gfabase
  license: Apache License 2.0
  summary: GFA insert into GenomicSQLite
  description: >
    gfabase is a command-line tool for indexed storage of Graphical Fragment Assembly (GFA1) data

extra:
  additional-platforms:
    - linux-aarch64
  recipe-maintainers:
    - aryarm
  skip-lints:
    - should_be_noarch_generic  # Rust's `cargo build` command makes this not a noarch recipe.
