{% set name = "finemap" %}
{% set version = "1.4.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  {% if linux %}
  url: http://www.christianbenner.com/finemap_v{{ version }}_x86_64.tgz
  sha256: 3b1fc6eb3c2ccafd647b32e02d0244495cd0ade9ed7d474606c31ebf6e98b0c9
  {% elif osx %}
  url: http://www.christianbenner.com/finemap_v{{ version }}_MacOSX.tgz
  sha256: e2967e5586347a8ac5cbcddf3c0e41bf8d3e7793875f78b509d07903d17a415b
  {% endif %}

build:
  binary_relocation: false
  number: 0
  script:
    - mkdir -p ${PREFIX}/bin
    - install -m 755 finemap_v{{ version }}_{{ "x86_64" if linux else "MacOSX" }} ${PREFIX}/bin/finemap

requirements:
  build:
    - {{ compiler('c') }}
  host: []
  run: []

test:
  commands:
    - finemap --help

about:
  home: http://www.christianbenner.com
  license: Other
  license_file: LICENSE
  summary: >
    Program for identifying causal SNPs and their effect sizes and heritability contributions

extra:
  recipe-maintainers:
    - danielnachun
