{% set name = "gbz-base" %}
{% set version = "0.6.0" %}
{% set vtag = "v0.6" %}
{% set sha256 = "bd7c13cefdce110439ad213f959b00c550768cecc517519c7bd1268d237367c1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jltsiren/{{ name }}/archive/refs/tags/{{ vtag }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage('gbz-base', max_pin="x.x") }}
  script:
    - export CFLAGS="${CFLAGS} -mavx -mavx2"  # [x86_64]
    - export RUSTFLAGS="${RUSTFLAGS} -C target-feature=+avx,+avx2"  # [x86_64]
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - RUST_BACKTRACE=1 CARGO_PROFILE_RELEASE_STRIP=symbols CARGO_PROFILE_RELEASE_LTO=fat cargo install --no-track --locked --root "${PREFIX}" --path .

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - gbz-base -h
    - gaf-base -h

about:
  home: https://github.com/jltsiren/gbz-base
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Prototype for an immutable pangenome graph in SQLite
  description: >
    This is a prototype for storing a GBZ graph in an SQLite database.
    It is intended for interactive applications, where you want to access
    parts of the graph immediately without loading the entire graph into memory.

extra:
  additional-platforms:
    - osx-arm64
    - linux-aarch64
  recipe-maintainers:
    - aryarm

