{% set name = "gbz-base" %}
{% set version = "0.2.0" %}
{% set vtag = "v0.2" %}
{% set sha256 = "e4a541857f7785f827ce45472f83c34490d141d114e9c66ef6e49f058acba5a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jltsiren/{{ name }}/archive/{{ vtag }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('gbz-base', max_pin="x.x") }}
  script:
    - RUST_BACKTRACE=1 CARGO_HOME="${BUILD_PREFIX}/.cargo" cargo build --release
    - mkdir -p "${PREFIX}/bin"
    - cp target/*/release/{query,gaf2db,gbz2db} "${PREFIX}/bin"

requirements:
  build:
    - {{ compiler('rust') }}

test:
  commands:
    - query -h
    - gbz2db -h
    - gaf2db -h

about:
  home: https://github.com/jltsiren/gbz-base
  license: MIT
  summary: Prototype for an immutable pangenome graph in SQLite
  description: >
    This is a prototype for storing a GBZ graph in an SQLite database.
    It is intended for interactive applications, where you want to access
    parts of the graph immediately without loading the entire graph into memory.

extra:
  additional-platforms:
    - osx-arm64
    - linux-aarch64
  recipe-maintainers:
    - aryarm
  skip-lints:
    - should_be_noarch_generic  # Rust's `cargo build` command makes this not a noarch recipe
