{% set name = "gbz-base" %}
{% set version = "0.4.0" %}
{% set vtag = "v0.4" %}
{% set sha256 = "78a3d16056296c49e4a8649ded5b7f663688e2414ea0b0d23a479f3a1aeeaf14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jltsiren/{{ name }}/archive/{{ vtag }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('gbz-base', max_pin="x.x") }}
  script:
    - RUST_BACKTRACE=1 CARGO_PROFILE_RELEASE_STRIP=symbols CARGO_PROFILE_RELEASE_LTO=fat cargo install --no-track --locked --root "${PREFIX}" --path .

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}

test:
  commands:
    - query -h
    - gbz2db -h
    - gaf2db -h
    - db2gaf -h

about:
  home: https://github.com/jltsiren/gbz-base
  license: MIT
  summary: Prototype for an immutable pangenome graph in SQLite
  description: >
    This is a prototype for storing a GBZ graph in an SQLite database.
    It is intended for interactive applications, where you want to access
    parts of the graph immediately without loading the entire graph into memory.

extra:
  additional-platforms:
    - osx-arm64
    - linux-aarch64
  recipe-maintainers:
    - aryarm
  skip-lints:
    - should_be_noarch_generic  # Rust's `cargo build` command makes this not a noarch recipe
