{% set name = "gbz-base" %}
{% set version = "0.1.0" %}
{% set vcommit = "2347fffab2212351c666f5ba5230c5a2eafa62e1" %}
{% set sha256 = "d17ef77d2f57ace316a7b35d910c5cd73be2a0d70ec7fcd31f2d0e3afbe1273c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jltsiren/{{ name }}/archive/{{ vcommit }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('gbz-base', max_pin="x.x") }}
  script:
    - cargo build --release
    - mv target/release/query "${PREFIX}/bin"
    - mv target/release/gbz2db "${PREFIX}/bin"

requirements:
  build:
    - git
    - rust

test:
  commands:
    - query -h
    - gbz2db -h

about:
  home: https://github.com/jltsiren/gbz-base
  license: MIT
  summary: Prototype for an immutable pangenome graph in SQLite
  description: >
    This is a prototype for storing a GBZ graph in an SQLite database.
    It is intended for interactive applications, where you want to access
    parts of the graph immediately without loading the entire graph into memory.

extra:
  additional-platforms:
    - linux-aarch64
  recipe-maintainers:
    - aryarm
  skip-lints:
    - should_be_noarch_generic  # Rust's `cargo build` command makes this not a noarch recipe.
