name: Tests

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
    paths-ignore:
      - 'README.md'
      - '.github/bioconda.yml'
      - '.devcontainer.json'
      - 'LICENSE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.github/bioconda.yml'
      - '.devcontainer.json'
      - 'LICENSE'
  workflow_dispatch:
    inputs:
      packagename:
        description: 'Package name to build'
        required: true
        type: string

jobs:
  # adapted from https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-object
  get_dirs:
    name: List changed recipes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    strategy:
      fail-fast: true
    outputs:
       # contains a list of the module names encoded as a json array
      matrix: ${{ steps.output-dirs-manual.outputs.matrix || steps.output-dirs-auto.outputs.matrix }}
      has_token: ${{ steps.token.outputs.has_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: List changed packages
        id: filter
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: dorny/paths-filter@v4
        with:
          list-files: shell
          filters: |
            changed:
              - added|modified: 'recipes/**'

      - name: Get directory names
        if: ${{ github.event_name != 'workflow_dispatch' }}
        id: output-dirs-auto
        run: |
          matrix=$(for i in ${{ steps.filter.outputs.changed_files }}; do sed 's\recipes/\\;s\/.*$\\' <<< $i; done | sort -u | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')
          echo "$matrix"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

      - name: Set matrix from manual input
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: output-dirs-manual
        run: |
          matrix=$(jq -cn --arg pkg "${{ inputs.packagename }}" '[$pkg]')
          echo "$matrix"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

      - name: Check for secret token
        id: token
        env:
          TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          echo "has_token=${{ env.TOKEN != '' }}" >> $GITHUB_OUTPUT

  build:
    name: Build on ${{ matrix.os }}
    needs: get_dirs
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    if: ${{ needs.get_dirs.outputs.matrix != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-15-intel, macos-latest, ubuntu-24.04-arm]
        packagename: ${{ fromJson(needs.get_dirs.outputs.matrix) }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v4
        with:
          activate-environment: biobuild
          channels: conda-forge,bioconda,defaults
          miniforge-version: latest
          use-mamba: true

      - name: Get Date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Conda env
        uses: actions/cache@v6
        with:
          path: ${{ env.CONDA }}/envs
          key: conda-${{ runner.os }}--${{ runner.arch }}--${{ steps.get-date.outputs.today }}-${{ env.CACHE_NUMBER }}
        env:
          CACHE_NUMBER: 0
        id: cache

      - name: Install biobuild environment
        shell: bash -el {0}
        run: mamba create -y -n biobuild -c conda-forge -c bioconda -c nodefaults bioconda-utils
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Lint
        shell: bash -el {0}
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: bioconda-utils lint --packages ${{ matrix.packagename }}

      - name: Run test
        shell: bash -el {0}
        run: |
          bioconda-utils build ${{ (startsWith(matrix.os, 'ubuntu') && format('--docker --mulled-test --docker-base-image quay.io/bioconda/bioconda-utils-build-env-cos7{0}', (endsWith(matrix.os, '-arm') && '-aarch64') || '')) || '' }} --packages ${{ matrix.packagename }}

      - name: Upload built package as GitHub artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.packagename }}-${{ matrix.os }}
          path: ${{ env.CONDA }}/envs/biobuild/conda-bld/
          if-no-files-found: ignore

  publish:
    name: Publish to Anaconda
    needs: [get_dirs, build]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'workflow_dispatch' && needs.get_dirs.outputs.matrix != '[]' && needs.get_dirs.outputs.has_token == 'true' }}
    env:
      ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
    steps:
      - name: Download all built artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./dist
          merge-multiple: true

      - name: Publish all packages to Anaconda
        uses: anaconda/actions/upload-package@latest
        with:
          token: ${{ secrets.ANACONDA_API_TOKEN }}
          channel: ${{ github.actor }} # assumes your Anaconda.org username is the same as your GitHub username
          force: true
          packages: ./dist/**/*.conda
